/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApiKeyGenerateNewApiKeyResponseData
 */
public class ApiKeyGenerateNewApiKeyResponseDataTest {
    private final ApiKeyGenerateNewApiKeyResponseData model = new ApiKeyGenerateNewApiKeyResponseData();

    /**
     * Model tests for ApiKeyGenerateNewApiKeyResponseData
     */
    @Test
    public void testApiKeyGenerateNewApiKeyResponseData() {
        // TODO: test ApiKeyGenerateNewApiKeyResponseData
    }

    /**
     * Test the property 'expires'
     */
    @Test
    public void expiresTest() {
        // TODO: test expires
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

}
