/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BalanceGetAccountBalanceResponseData
 */
public class BalanceGetAccountBalanceResponseDataTest {
    private final BalanceGetAccountBalanceResponseData model = new BalanceGetAccountBalanceResponseData();

    /**
     * Model tests for BalanceGetAccountBalanceResponseData
     */
    @Test
    public void testBalanceGetAccountBalanceResponseData() {
        // TODO: test BalanceGetAccountBalanceResponseData
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'txnCount'
     */
    @Test
    public void txnCountTest() {
        // TODO: test txnCount
    }

}
