/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BalanceGetAccountBalance200ResponseDataBalances
 */
public class BalanceGetAccountBalance200ResponseDataBalancesTest {
    private final BalanceGetAccountBalance200ResponseDataBalances model = new BalanceGetAccountBalance200ResponseDataBalances();

    /**
     * Model tests for BalanceGetAccountBalance200ResponseDataBalances
     */
    @Test
    public void testBalanceGetAccountBalance200ResponseDataBalances() {
        // TODO: test BalanceGetAccountBalance200ResponseDataBalances
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'formattedAmount'
     */
    @Test
    public void formattedAmountTest() {
        // TODO: test formattedAmount
    }

    /**
     * Test the property 'toCurrency'
     */
    @Test
    public void toCurrencyTest() {
        // TODO: test toCurrency
    }

    /**
     * Test the property 'totalRecieved'
     */
    @Test
    public void totalRecievedTest() {
        // TODO: test totalRecieved
    }

    /**
     * Test the property 'totalSent'
     */
    @Test
    public void totalSentTest() {
        // TODO: test totalSent
    }

    /**
     * Test the property 'txnCount'
     */
    @Test
    public void txnCountTest() {
        // TODO: test txnCount
    }

}
