/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BankAccountVerifyAndReturnDetailsResponseData
 */
public class BankAccountVerifyAndReturnDetailsResponseDataTest {
    private final BankAccountVerifyAndReturnDetailsResponseData model = new BankAccountVerifyAndReturnDetailsResponseData();

    /**
     * Model tests for BankAccountVerifyAndReturnDetailsResponseData
     */
    @Test
    public void testBankAccountVerifyAndReturnDetailsResponseData() {
        // TODO: test BankAccountVerifyAndReturnDetailsResponseData
    }

    /**
     * Test the property 'accountname'
     */
    @Test
    public void accountnameTest() {
        // TODO: test accountname
    }

    /**
     * Test the property 'accountnumber'
     */
    @Test
    public void accountnumberTest() {
        // TODO: test accountnumber
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'internalreference'
     */
    @Test
    public void internalreferenceTest() {
        // TODO: test internalreference
    }

    /**
     * Test the property 'isTrashed'
     */
    @Test
    public void isTrashedTest() {
        // TODO: test isTrashed
    }

    /**
     * Test the property 'isVisible'
     */
    @Test
    public void isVisibleTest() {
        // TODO: test isVisible
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'phonenumber'
     */
    @Test
    public void phonenumberTest() {
        // TODO: test phonenumber
    }

    /**
     * Test the property 'responsecode'
     */
    @Test
    public void responsecodeTest() {
        // TODO: test responsecode
    }

    /**
     * Test the property 'responsemessage'
     */
    @Test
    public void responsemessageTest() {
        // TODO: test responsemessage
    }

    /**
     * Test the property 'uniquereference'
     */
    @Test
    public void uniquereferenceTest() {
        // TODO: test uniquereference
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
