/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CurrencyListSupportedCurrenciesResponseData
 */
public class CurrencyListSupportedCurrenciesResponseDataTest {
    private final CurrencyListSupportedCurrenciesResponseData model = new CurrencyListSupportedCurrenciesResponseData();

    /**
     * Model tests for CurrencyListSupportedCurrenciesResponseData
     */
    @Test
    public void testCurrencyListSupportedCurrenciesResponseData() {
        // TODO: test CurrencyListSupportedCurrenciesResponseData
    }

    /**
     * Test the property 'incomingCurrencies'
     */
    @Test
    public void incomingCurrenciesTest() {
        // TODO: test incomingCurrencies
    }

    /**
     * Test the property 'outgoingCurrencies'
     */
    @Test
    public void outgoingCurrenciesTest() {
        // TODO: test outgoingCurrencies
    }

}
