/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantsUpdateRecordResponseData
 */
public class MerchantsUpdateRecordResponseDataTest {
    private final MerchantsUpdateRecordResponseData model = new MerchantsUpdateRecordResponseData();

    /**
     * Model tests for MerchantsUpdateRecordResponseData
     */
    @Test
    public void testMerchantsUpdateRecordResponseData() {
        // TODO: test MerchantsUpdateRecordResponseData
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'creditCurrency'
     */
    @Test
    public void creditCurrencyTest() {
        // TODO: test creditCurrency
    }

    /**
     * Test the property 'feeBearer'
     */
    @Test
    public void feeBearerTest() {
        // TODO: test feeBearer
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

}
