/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentCreateNewPaymentRequest
 */
public class PaymentCreateNewPaymentRequestTest {
    private final PaymentCreateNewPaymentRequest model = new PaymentCreateNewPaymentRequest();

    /**
     * Model tests for PaymentCreateNewPaymentRequest
     */
    @Test
    public void testPaymentCreateNewPaymentRequest() {
        // TODO: test PaymentCreateNewPaymentRequest
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'bank'
     */
    @Test
    public void bankTest() {
        // TODO: test bank
    }

    /**
     * Test the property 'bankCode'
     */
    @Test
    public void bankCodeTest() {
        // TODO: test bankCode
    }

    /**
     * Test the property 'businessId'
     */
    @Test
    public void businessIdTest() {
        // TODO: test businessId
    }

    /**
     * Test the property 'coinprofileUsername'
     */
    @Test
    public void coinprofileUsernameTest() {
        // TODO: test coinprofileUsername
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'customerEmail'
     */
    @Test
    public void customerEmailTest() {
        // TODO: test customerEmail
    }

    /**
     * Test the property 'incomingAmount'
     */
    @Test
    public void incomingAmountTest() {
        // TODO: test incomingAmount
    }

    /**
     * Test the property 'incomingCurrency'
     */
    @Test
    public void incomingCurrencyTest() {
        // TODO: test incomingCurrency
    }

    /**
     * Test the property 'outgoingAmount'
     */
    @Test
    public void outgoingAmountTest() {
        // TODO: test outgoingAmount
    }

    /**
     * Test the property 'outgoingCurrency'
     */
    @Test
    public void outgoingCurrencyTest() {
        // TODO: test outgoingCurrency
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'rateKey'
     */
    @Test
    public void rateKeyTest() {
        // TODO: test rateKey
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

}
