/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentCreateNewPaymentResponseData
 */
public class PaymentCreateNewPaymentResponseDataTest {
    private final PaymentCreateNewPaymentResponseData model = new PaymentCreateNewPaymentResponseData();

    /**
     * Model tests for PaymentCreateNewPaymentResponseData
     */
    @Test
    public void testPaymentCreateNewPaymentResponseData() {
        // TODO: test PaymentCreateNewPaymentResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'businessId'
     */
    @Test
    public void businessIdTest() {
        // TODO: test businessId
    }

    /**
     * Test the property 'confirmedAmount'
     */
    @Test
    public void confirmedAmountTest() {
        // TODO: test confirmedAmount
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'customerEmail'
     */
    @Test
    public void customerEmailTest() {
        // TODO: test customerEmail
    }

    /**
     * Test the property 'expTime'
     */
    @Test
    public void expTimeTest() {
        // TODO: test expTime
    }

    /**
     * Test the property 'incomingAmount'
     */
    @Test
    public void incomingAmountTest() {
        // TODO: test incomingAmount
    }

    /**
     * Test the property 'incomingCurrency'
     */
    @Test
    public void incomingCurrencyTest() {
        // TODO: test incomingCurrency
    }

    /**
     * Test the property 'outgoingAmount'
     */
    @Test
    public void outgoingAmountTest() {
        // TODO: test outgoingAmount
    }

    /**
     * Test the property 'outgoingCurrency'
     */
    @Test
    public void outgoingCurrencyTest() {
        // TODO: test outgoingCurrency
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'senderUsername'
     */
    @Test
    public void senderUsernameTest() {
        // TODO: test senderUsername
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'threadTS'
     */
    @Test
    public void threadTSTest() {
        // TODO: test threadTS
    }

    /**
     * Test the property 'unconfirmedAmount'
     */
    @Test
    public void unconfirmedAmountTest() {
        // TODO: test unconfirmedAmount
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
