/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionsGetMerchantTransactionSummaryResponseData
 */
public class TransactionsGetMerchantTransactionSummaryResponseDataTest {
    private final TransactionsGetMerchantTransactionSummaryResponseData model = new TransactionsGetMerchantTransactionSummaryResponseData();

    /**
     * Model tests for TransactionsGetMerchantTransactionSummaryResponseData
     */
    @Test
    public void testTransactionsGetMerchantTransactionSummaryResponseData() {
        // TODO: test TransactionsGetMerchantTransactionSummaryResponseData
    }

    /**
     * Test the property 'totalPaid'
     */
    @Test
    public void totalPaidTest() {
        // TODO: test totalPaid
    }

    /**
     * Test the property 'totalRedeemed'
     */
    @Test
    public void totalRedeemedTest() {
        // TODO: test totalRedeemed
    }

    /**
     * Test the property 'totalUnpaid'
     */
    @Test
    public void totalUnpaidTest() {
        // TODO: test totalUnpaid
    }

    /**
     * Test the property 'totalUnredeemed'
     */
    @Test
    public void totalUnredeemedTest() {
        // TODO: test totalUnredeemed
    }

}
