/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionGetUserTransactionSummaryResponseDataSummary
 */
public class TransactionGetUserTransactionSummaryResponseDataSummaryTest {
    private final TransactionGetUserTransactionSummaryResponseDataSummary model = new TransactionGetUserTransactionSummaryResponseDataSummary();

    /**
     * Model tests for TransactionGetUserTransactionSummaryResponseDataSummary
     */
    @Test
    public void testTransactionGetUserTransactionSummaryResponseDataSummary() {
        // TODO: test TransactionGetUserTransactionSummaryResponseDataSummary
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'txnCount'
     */
    @Test
    public void txnCountTest() {
        // TODO: test txnCount
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

}
