/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransactionGetDetailsResponse
 */
public class TransactionGetDetailsResponseTest {
    private final TransactionGetDetailsResponse model = new TransactionGetDetailsResponse();

    /**
     * Model tests for TransactionGetDetailsResponse
     */
    @Test
    public void testTransactionGetDetailsResponse() {
        // TODO: test TransactionGetDetailsResponse
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'businessId'
     */
    @Test
    public void businessIdTest() {
        // TODO: test businessId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'fromAmount'
     */
    @Test
    public void fromAmountTest() {
        // TODO: test fromAmount
    }

    /**
     * Test the property 'fromCurrency'
     */
    @Test
    public void fromCurrencyTest() {
        // TODO: test fromCurrency
    }

    /**
     * Test the property 'isFromRegUser'
     */
    @Test
    public void isFromRegUserTest() {
        // TODO: test isFromRegUser
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'prevBalance'
     */
    @Test
    public void prevBalanceTest() {
        // TODO: test prevBalance
    }

    /**
     * Test the property 'sender'
     */
    @Test
    public void senderTest() {
        // TODO: test sender
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

}
