/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoucherRedeemExistingUnusedResponseData
 */
public class VoucherRedeemExistingUnusedResponseDataTest {
    private final VoucherRedeemExistingUnusedResponseData model = new VoucherRedeemExistingUnusedResponseData();

    /**
     * Model tests for VoucherRedeemExistingUnusedResponseData
     */
    @Test
    public void testVoucherRedeemExistingUnusedResponseData() {
        // TODO: test VoucherRedeemExistingUnusedResponseData
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'feeBearer'
     */
    @Test
    public void feeBearerTest() {
        // TODO: test feeBearer
    }

    /**
     * Test the property 'fromAmount'
     */
    @Test
    public void fromAmountTest() {
        // TODO: test fromAmount
    }

    /**
     * Test the property 'fromCurrency'
     */
    @Test
    public void fromCurrencyTest() {
        // TODO: test fromCurrency
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'previousBalance'
     */
    @Test
    public void previousBalanceTest() {
        // TODO: test previousBalance
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'toAmount'
     */
    @Test
    public void toAmountTest() {
        // TODO: test toAmount
    }

    /**
     * Test the property 'toCurrency'
     */
    @Test
    public void toCurrencyTest() {
        // TODO: test toCurrency
    }

    /**
     * Test the property 'voucherCode'
     */
    @Test
    public void voucherCodeTest() {
        // TODO: test voucherCode
    }

    /**
     * Test the property 'wavedFee'
     */
    @Test
    public void wavedFeeTest() {
        // TODO: test wavedFee
    }

}
