/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoucherGetRecordResponseDataInner
 */
public class VoucherGetRecordResponseDataInnerTest {
    private final VoucherGetRecordResponseDataInner model = new VoucherGetRecordResponseDataInner();

    /**
     * Model tests for VoucherGetRecordResponseDataInner
     */
    @Test
    public void testVoucherGetRecordResponseDataInner() {
        // TODO: test VoucherGetRecordResponseDataInner
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'cancelledAt'
     */
    @Test
    public void cancelledAtTest() {
        // TODO: test cancelledAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'dateRedeemed'
     */
    @Test
    public void dateRedeemedTest() {
        // TODO: test dateRedeemed
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'feeBearer'
     */
    @Test
    public void feeBearerTest() {
        // TODO: test feeBearer
    }

    /**
     * Test the property 'fullname'
     */
    @Test
    public void fullnameTest() {
        // TODO: test fullname
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'memo'
     */
    @Test
    public void memoTest() {
        // TODO: test memo
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'paymentExpiresAt'
     */
    @Test
    public void paymentExpiresAtTest() {
        // TODO: test paymentExpiresAt
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    public void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'voucherCode'
     */
    @Test
    public void voucherCodeTest() {
        // TODO: test voucherCode
    }

}
