/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN
 */
public class VoucherMinmaxAmountGetMinMaxAmountResponseDataNGNTest {
    private final VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN model = new VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN();

    /**
     * Model tests for VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN
     */
    @Test
    public void testVoucherMinmaxAmountGetMinMaxAmountResponseDataNGN() {
        // TODO: test VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

}
