/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoucherRedeemAndWithdrawResponseData
 */
public class VoucherRedeemAndWithdrawResponseDataTest {
    private final VoucherRedeemAndWithdrawResponseData model = new VoucherRedeemAndWithdrawResponseData();

    /**
     * Model tests for VoucherRedeemAndWithdrawResponseData
     */
    @Test
    public void testVoucherRedeemAndWithdrawResponseData() {
        // TODO: test VoucherRedeemAndWithdrawResponseData
    }

    /**
     * Test the property 'convertedVoucherFee'
     */
    @Test
    public void convertedVoucherFeeTest() {
        // TODO: test convertedVoucherFee
    }

    /**
     * Test the property 'convertedVoucherFeeCurrency'
     */
    @Test
    public void convertedVoucherFeeCurrencyTest() {
        // TODO: test convertedVoucherFeeCurrency
    }

    /**
     * Test the property 'creditCurrency'
     */
    @Test
    public void creditCurrencyTest() {
        // TODO: test creditCurrency
    }

    /**
     * Test the property 'currentBalance'
     */
    @Test
    public void currentBalanceTest() {
        // TODO: test currentBalance
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'feeBearer'
     */
    @Test
    public void feeBearerTest() {
        // TODO: test feeBearer
    }

    /**
     * Test the property 'fromAmount'
     */
    @Test
    public void fromAmountTest() {
        // TODO: test fromAmount
    }

    /**
     * Test the property 'fromCurrency'
     */
    @Test
    public void fromCurrencyTest() {
        // TODO: test fromCurrency
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'merchantFee'
     */
    @Test
    public void merchantFeeTest() {
        // TODO: test merchantFee
    }

    /**
     * Test the property 'previousBalance'
     */
    @Test
    public void previousBalanceTest() {
        // TODO: test previousBalance
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'toAccount'
     */
    @Test
    public void toAccountTest() {
        // TODO: test toAccount
    }

    /**
     * Test the property 'toAmount'
     */
    @Test
    public void toAmountTest() {
        // TODO: test toAmount
    }

    /**
     * Test the property 'toCurrency'
     */
    @Test
    public void toCurrencyTest() {
        // TODO: test toCurrency
    }

    /**
     * Test the property 'voucherCode'
     */
    @Test
    public void voucherCodeTest() {
        // TODO: test voucherCode
    }

    /**
     * Test the property 'voucherFee'
     */
    @Test
    public void voucherFeeTest() {
        // TODO: test voucherFee
    }

    /**
     * Test the property 'withdrawalFee'
     */
    @Test
    public void withdrawalFeeTest() {
        // TODO: test withdrawalFee
    }

}
