/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN;
import com.konfigthis.client.model.VoucherMinmaxAmountGetMinMaxAmountResponseDataUSD;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VoucherMinmaxAmountGetMinMaxAmountResponseData
 */
public class VoucherMinmaxAmountGetMinMaxAmountResponseDataTest {
    private final VoucherMinmaxAmountGetMinMaxAmountResponseData model = new VoucherMinmaxAmountGetMinMaxAmountResponseData();

    /**
     * Model tests for VoucherMinmaxAmountGetMinMaxAmountResponseData
     */
    @Test
    public void testVoucherMinmaxAmountGetMinMaxAmountResponseData() {
        // TODO: test VoucherMinmaxAmountGetMinMaxAmountResponseData
    }

    /**
     * Test the property 'NGN'
     */
    @Test
    public void NGNTest() {
        // TODO: test NGN
    }

    /**
     * Test the property 'USD'
     */
    @Test
    public void USDTest() {
        // TODO: test USD
    }

}
