/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TransactionGetUserTransactionSummaryResponseDataSummary
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TransactionGetUserTransactionSummaryResponseDataSummary {
  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private Double duration;

  public static final String SERIALIZED_NAME_TXN_COUNT = "txnCount";
  @SerializedName(SERIALIZED_NAME_TXN_COUNT)
  private Double txnCount;

  public static final String SERIALIZED_NAME_VOLUME = "volume";
  @SerializedName(SERIALIZED_NAME_VOLUME)
  private Double volume;

  public TransactionGetUserTransactionSummaryResponseDataSummary() {
  }

  public TransactionGetUserTransactionSummaryResponseDataSummary duration(Double duration) {
    
    
    
    
    this.duration = duration;
    return this;
  }

  public TransactionGetUserTransactionSummaryResponseDataSummary duration(Integer duration) {
    
    
    
    
    this.duration = duration.doubleValue();
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getDuration() {
    return duration;
  }


  public void setDuration(Double duration) {
    
    
    
    this.duration = duration;
  }


  public TransactionGetUserTransactionSummaryResponseDataSummary txnCount(Double txnCount) {
    
    
    
    
    this.txnCount = txnCount;
    return this;
  }

  public TransactionGetUserTransactionSummaryResponseDataSummary txnCount(Integer txnCount) {
    
    
    
    
    this.txnCount = txnCount.doubleValue();
    return this;
  }

   /**
   * Get txnCount
   * @return txnCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getTxnCount() {
    return txnCount;
  }


  public void setTxnCount(Double txnCount) {
    
    
    
    this.txnCount = txnCount;
  }


  public TransactionGetUserTransactionSummaryResponseDataSummary volume(Double volume) {
    
    
    
    
    this.volume = volume;
    return this;
  }

  public TransactionGetUserTransactionSummaryResponseDataSummary volume(Integer volume) {
    
    
    
    
    this.volume = volume.doubleValue();
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getVolume() {
    return volume;
  }


  public void setVolume(Double volume) {
    
    
    
    this.volume = volume;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TransactionGetUserTransactionSummaryResponseDataSummary instance itself
   */
  public TransactionGetUserTransactionSummaryResponseDataSummary putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionGetUserTransactionSummaryResponseDataSummary transactionGetUserTransactionSummaryResponseDataSummary = (TransactionGetUserTransactionSummaryResponseDataSummary) o;
    return Objects.equals(this.duration, transactionGetUserTransactionSummaryResponseDataSummary.duration) &&
        Objects.equals(this.txnCount, transactionGetUserTransactionSummaryResponseDataSummary.txnCount) &&
        Objects.equals(this.volume, transactionGetUserTransactionSummaryResponseDataSummary.volume)&&
        Objects.equals(this.additionalProperties, transactionGetUserTransactionSummaryResponseDataSummary.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, txnCount, volume, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionGetUserTransactionSummaryResponseDataSummary {\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    txnCount: ").append(toIndentedString(txnCount)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("duration");
    openapiFields.add("txnCount");
    openapiFields.add("volume");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TransactionGetUserTransactionSummaryResponseDataSummary
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TransactionGetUserTransactionSummaryResponseDataSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransactionGetUserTransactionSummaryResponseDataSummary is not found in the empty JSON string", TransactionGetUserTransactionSummaryResponseDataSummary.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransactionGetUserTransactionSummaryResponseDataSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransactionGetUserTransactionSummaryResponseDataSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransactionGetUserTransactionSummaryResponseDataSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransactionGetUserTransactionSummaryResponseDataSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<TransactionGetUserTransactionSummaryResponseDataSummary>() {
           @Override
           public void write(JsonWriter out, TransactionGetUserTransactionSummaryResponseDataSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TransactionGetUserTransactionSummaryResponseDataSummary read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TransactionGetUserTransactionSummaryResponseDataSummary instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TransactionGetUserTransactionSummaryResponseDataSummary given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TransactionGetUserTransactionSummaryResponseDataSummary
  * @throws IOException if the JSON string is invalid with respect to TransactionGetUserTransactionSummaryResponseDataSummary
  */
  public static TransactionGetUserTransactionSummaryResponseDataSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransactionGetUserTransactionSummaryResponseDataSummary.class);
  }

 /**
  * Convert an instance of TransactionGetUserTransactionSummaryResponseDataSummary to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

