/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * WalletGetSupportedConfigResponseData
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class WalletGetSupportedConfigResponseData {
  public static final String SERIALIZED_NAME_BY_CURRENCY = "byCurrency";
  @SerializedName(SERIALIZED_NAME_BY_CURRENCY)
  private Object byCurrency;

  public static final String SERIALIZED_NAME_BY_NETWORK = "byNetwork";
  @SerializedName(SERIALIZED_NAME_BY_NETWORK)
  private Object byNetwork;

  public WalletGetSupportedConfigResponseData() {
  }

  public WalletGetSupportedConfigResponseData byCurrency(Object byCurrency) {
    
    
    
    
    this.byCurrency = byCurrency;
    return this;
  }

   /**
   * Get byCurrency
   * @return byCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getByCurrency() {
    return byCurrency;
  }


  public void setByCurrency(Object byCurrency) {
    
    
    
    this.byCurrency = byCurrency;
  }


  public WalletGetSupportedConfigResponseData byNetwork(Object byNetwork) {
    
    
    
    
    this.byNetwork = byNetwork;
    return this;
  }

   /**
   * Get byNetwork
   * @return byNetwork
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getByNetwork() {
    return byNetwork;
  }


  public void setByNetwork(Object byNetwork) {
    
    
    
    this.byNetwork = byNetwork;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WalletGetSupportedConfigResponseData instance itself
   */
  public WalletGetSupportedConfigResponseData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletGetSupportedConfigResponseData walletGetSupportedConfigResponseData = (WalletGetSupportedConfigResponseData) o;
    return Objects.equals(this.byCurrency, walletGetSupportedConfigResponseData.byCurrency) &&
        Objects.equals(this.byNetwork, walletGetSupportedConfigResponseData.byNetwork)&&
        Objects.equals(this.additionalProperties, walletGetSupportedConfigResponseData.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byCurrency, byNetwork, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletGetSupportedConfigResponseData {\n");
    sb.append("    byCurrency: ").append(toIndentedString(byCurrency)).append("\n");
    sb.append("    byNetwork: ").append(toIndentedString(byNetwork)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("byCurrency");
    openapiFields.add("byNetwork");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to WalletGetSupportedConfigResponseData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!WalletGetSupportedConfigResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WalletGetSupportedConfigResponseData is not found in the empty JSON string", WalletGetSupportedConfigResponseData.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WalletGetSupportedConfigResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WalletGetSupportedConfigResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WalletGetSupportedConfigResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WalletGetSupportedConfigResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<WalletGetSupportedConfigResponseData>() {
           @Override
           public void write(JsonWriter out, WalletGetSupportedConfigResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WalletGetSupportedConfigResponseData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             WalletGetSupportedConfigResponseData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WalletGetSupportedConfigResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WalletGetSupportedConfigResponseData
  * @throws IOException if the JSON string is invalid with respect to WalletGetSupportedConfigResponseData
  */
  public static WalletGetSupportedConfigResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WalletGetSupportedConfigResponseData.class);
  }

 /**
  * Convert an instance of WalletGetSupportedConfigResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

