/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BankAccountVerifyAndReturnDetailsRequest;
import com.konfigthis.client.model.BankAccountVerifyAndReturnDetailsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BankAccountApi
 */
@Disabled
public class BankAccountApiTest {

    private static BankAccountApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BankAccountApi(apiClient);
    }

    /**
     * Resolve bank account
     *
     * Verifies the bank account and returns the bank account details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyAndReturnDetailsTest() throws ApiException {
        String accountNumber = null;
        String bankCode = null;
        BankAccountVerifyAndReturnDetailsResponse response = api.verifyAndReturnDetails(accountNumber, bankCode)
                .execute();
        // TODO: test validations
    }

}
