/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.TransactionsGetMerchantTransactionSummaryResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionsApi
 */
@Disabled
public class TransactionsApiTest {

    private static TransactionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TransactionsApi(apiClient);
    }

    /**
     * Retrieve merchant transaction summary
     *
     * Retrieves transaction summary for the selected currency for a merchant
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMerchantTransactionSummaryTest() throws ApiException {
        String currency = null;
        TransactionsGetMerchantTransactionSummaryResponse response = api.getMerchantTransactionSummary(currency)
                .execute();
        // TODO: test validations
    }

}
