/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.VoucherMinmaxAmountGetMinMaxAmountResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VoucherMinMaxAmountApi
 */
@Disabled
public class VoucherMinMaxAmountApiTest {

    private static VoucherMinMaxAmountApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new VoucherMinMaxAmountApi(apiClient);
    }

    /**
     * Retrieves minimum and maximum voucher amounts
     *
     * Retrieves minimum and maximum voucher amounts for each currency.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMinMaxAmountTest() throws ApiException {
        String currency = null;
        VoucherMinmaxAmountGetMinMaxAmountResponse response = api.getMinMaxAmount()
                .currency(currency)
                .execute();
        // TODO: test validations
    }

}
