/*
 * Coinprofile business API
 * Coinprofile business API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.MockPaymentRequestSubmissionRequest;
import com.konfigthis.client.model.MockPaymentRequestSubmissionResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class MockPaymentApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MockPaymentApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public MockPaymentApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call requestSubmissionCall(MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = mockPaymentRequestSubmissionRequest;

        // create path and map variables
        String localVarPath = "/v1/mock/payment";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call requestSubmissionValidateBeforeCall(MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'mockPaymentRequestSubmissionRequest' is set
        if (mockPaymentRequestSubmissionRequest == null) {
            throw new ApiException("Missing the required parameter 'mockPaymentRequestSubmissionRequest' when calling requestSubmission(Async)");
        }

        return requestSubmissionCall(mockPaymentRequestSubmissionRequest, _callback);

    }


    private ApiResponse<MockPaymentRequestSubmissionResponse> requestSubmissionWithHttpInfo(MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest) throws ApiException {
        okhttp3.Call localVarCall = requestSubmissionValidateBeforeCall(mockPaymentRequestSubmissionRequest, null);
        Type localVarReturnType = new TypeToken<MockPaymentRequestSubmissionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call requestSubmissionAsync(MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest, final ApiCallback<MockPaymentRequestSubmissionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = requestSubmissionValidateBeforeCall(mockPaymentRequestSubmissionRequest, _callback);
        Type localVarReturnType = new TypeToken<MockPaymentRequestSubmissionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class RequestSubmissionRequestBuilder {
        private final String voucherId;
        private Integer amount;

        private RequestSubmissionRequestBuilder(String voucherId) {
            this.voucherId = voucherId;
        }

        /**
         * Set amount
         * @param amount Amount to pay. This can be used to simulate overpayment and underpayment in staging environment. If this field is not provided, the expected amount will be paid. (optional)
         * @return RequestSubmissionRequestBuilder
         */
        public RequestSubmissionRequestBuilder amount(Integer amount) {
            this.amount = amount;
            return this;
        }
        
        /**
         * Build call for requestSubmission
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> successful operation </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest = buildBodyParams();
            return requestSubmissionCall(mockPaymentRequestSubmissionRequest, _callback);
        }

        private MockPaymentRequestSubmissionRequest buildBodyParams() {
            MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest = new MockPaymentRequestSubmissionRequest();
            mockPaymentRequestSubmissionRequest.amount(this.amount);
            mockPaymentRequestSubmissionRequest.voucherId(this.voucherId);
            return mockPaymentRequestSubmissionRequest;
        }

        /**
         * Execute requestSubmission request
         * @return MockPaymentRequestSubmissionResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> successful operation </td><td>  -  </td></tr>
         </table>
         */
        public MockPaymentRequestSubmissionResponse execute() throws ApiException {
            MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest = buildBodyParams();
            ApiResponse<MockPaymentRequestSubmissionResponse> localVarResp = requestSubmissionWithHttpInfo(mockPaymentRequestSubmissionRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute requestSubmission request with HTTP info returned
         * @return ApiResponse&lt;MockPaymentRequestSubmissionResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> successful operation </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<MockPaymentRequestSubmissionResponse> executeWithHttpInfo() throws ApiException {
            MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest = buildBodyParams();
            return requestSubmissionWithHttpInfo(mockPaymentRequestSubmissionRequest);
        }

        /**
         * Execute requestSubmission request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> successful operation </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<MockPaymentRequestSubmissionResponse> _callback) throws ApiException {
            MockPaymentRequestSubmissionRequest mockPaymentRequestSubmissionRequest = buildBodyParams();
            return requestSubmissionAsync(mockPaymentRequestSubmissionRequest, _callback);
        }
    }

    /**
     * Make a mock payment
     * Sends a mock payment request (only in staging environment)
     * @param mockPaymentRequestSubmissionRequest  (required)
     * @return RequestSubmissionRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public RequestSubmissionRequestBuilder requestSubmission(String voucherId) throws IllegalArgumentException {
        if (voucherId == null) throw new IllegalArgumentException("\"voucherId\" is required but got null");
            

        return new RequestSubmissionRequestBuilder(voucherId);
    }
}
